- project:
    name: ceph-volume-nightly-lvm
    distro:
      - xenial
      - centos7
      - centos8
    objectstore:
      - bluestore
      - filestore
    scenario:
      - create
      - dmcrypt
    subcommand:
      - lvm
    ceph_branch:
      - main
      - nautilus
    exclude:
      - ceph_branch: main
        distro: centos7
      - ceph_branch: nautilus
        distro: centos8
      - ceph_branch: main
        distro: xenial
      - ceph_branch: nautilus
        distro: xenial

    jobs:
      - 'ceph-volume-nightly-{ceph_branch}-{subcommand}-{distro}-{objectstore}-{scenario}'

- project:
    name: ceph-volume-nightly-batch
    distro:
      - xenial
      - centos7
      - centos8
    objectstore:
      - bluestore
      - filestore
    scenario:
      - single_type
      - single_type_dmcrypt
    subcommand:
      - batch
    ceph_branch:
      - main
      - nautilus
    exclude:
      - ceph_branch: main
        distro: centos7
      - ceph_branch: nautilus
        distro: centos8
      - ceph_branch: main
        distro: xenial
      - ceph_branch: nautilus
        distro: xenial

    jobs:
      - 'ceph-volume-nightly-{ceph_branch}-{subcommand}-{distro}-{objectstore}-{scenario}'

- project:
    name: ceph-volume-nightly-batch-mixed
    distro:
      - centos7
      - centos8
    objectstore:
      - bluestore
      - filestore
    scenario:
      - mixed_type
      - mixed_type_dmcrypt
      - mixed_type_explicit
      - mixed_type_dmcrypt_explicit
    subcommand:
      - batch
    ceph_branch:
      - main
      - nautilus
    exclude:
      - ceph_branch: main
        distro: centos7
      - ceph_branch: nautilus
        distro: centos8
      - ceph_branch: main
        distro: xenial
      - ceph_branch: nautilus
        distro: xenial

    jobs:
      - 'ceph-volume-nightly-{ceph_branch}-{subcommand}-{distro}-{objectstore}-{scenario}'


- job-template:
    name: 'ceph-volume-nightly-{ceph_branch}-{subcommand}-{distro}-{objectstore}-{scenario}'
    display-name: 'ceph-volume {ceph_branch} {subcommand}: [{distro}-{objectstore}-{scenario}]'
    node: vagrant&&libvirt&&(smithi||mira||irvingi)
    concurrent: true
    project-type: freestyle
    defaults: global
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    properties:
      - github:
          url: https://github.com/ceph/ceph
      - build-discarder:
          days-to-keep: 30
    discard-old-builds: true

    triggers:
      - timed: '@daily'

    scm:
      - git:
          url: https://github.com/ceph/ceph.git
          branches:
            - '{ceph_branch}'
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: true

    builders:
      - inject:
          properties-content: |
            SCENARIO={scenario}
            DISTRO={distro}
            OBJECTSTORE={objectstore}
            SUBCOMMAND={subcommand}
            CEPH_BRANCH={ceph_branch}
      - shell:
          !include-raw-escape:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw-escape:
                      - ../../../scripts/build_utils.sh
                      - ../../build/teardown

      - archive:
          artifacts: 'logs/**'
          allow-empty: true
          latest-only: false

      - email:
          recipients: aschoen@redhat.com gabrioux@redhat.com
