- job:
    name: "ceph-volume-test"
    description: 'This job will trigger all ceph-volume functional tests given a branch and sha1.'
    project-type: multijob
    defaults: global
    display-name: 'ceph-volume functional test suite'
    block-downstream: false
    block-upstream: false
    concurrent: true
    properties:
      - build-discarder:
          days-to-keep: 20
          artifact-num-to-keep: 20
      - github:
          url: https://github.com/ceph/ceph

    parameters:
      - string:
          name: CEPH_BRANCH
          description: "The ceph branch to test against"
          default: "main"
      - string:
          name: CEPH_SHA1
          description: "The ceph sha1 to test against"
          default: "latest"
      - string:
          name: CEPH_ANSIBLE_BRANCH
          description: "The ceph-ansible branch to test against"
          default: "main"
      - string:
          name: CEPH_REPO_URL
          description: "The full https url to clone from"
          default: "https://github.com/ceph/ceph.git"

    builders:
      # centos8 based jobs for octopus & pacific & main
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            set -x
            if [[ ! "$CEPH_BRANCH" =~ main|octopus|pacific ]]; then
              exit 1
            fi
          on-evaluation-failure: dont-run
          steps:
          - multijob:
              name: 'testing ceph-volume lvm'
              condition: SUCCESSFUL
              projects:
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-bluestore-create
                    SUBCOMMAND=lvm
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-filestore-create
                    SUBCOMMAND=lvm
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-bluestore-dmcrypt
                    SUBCOMMAND=lvm
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-filestore-dmcrypt
                    SUBCOMMAND=lvm
          - multijob:
              name: 'testing ceph-volume batch'
              condition: SUCCESSFUL
              projects:
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-bluestore-single_type
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-bluestore-single_type_dmcrypt
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-filestore-single_type
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-filestore-single_type_dmcrypt
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-bluestore-mixed_type
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-filestore-mixed_type
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-bluestore-mixed_type_dmcrypt
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-filestore-mixed_type_dmcrypt
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-bluestore-mixed_type_explicit
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-filestore-mixed_type_explicit
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-bluestore-mixed_type_dmcrypt_explicit
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos8-filestore-mixed_type_dmcrypt_explicit
                    SUBCOMMAND=batch

      # centos7 and xenial based jobs for pre-octopus releases
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            set -x
            # if the target branch is luminous or mimic we run these tests.
            if [[ ! "$CEPH_BRANCH" =~ luminous|mimic|nautilus ]]; then
              exit 1
            fi
          on-evaluation-failure: dont-run
          steps:
          - multijob:
              name: 'testing ceph-volume lvm'
              condition: SUCCESSFUL
              projects:
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-bluestore-create
                    SUBCOMMAND=lvm
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-filestore-create
                    SUBCOMMAND=lvm
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-bluestore-dmcrypt
                    SUBCOMMAND=lvm
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-filestore-dmcrypt
                    SUBCOMMAND=lvm

                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=xenial-bluestore-create
                    SUBCOMMAND=lvm
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=xenial-filestore-create
                    SUBCOMMAND=lvm
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=xenial-bluestore-dmcrypt
                    SUBCOMMAND=lvm
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=xenial-filestore-dmcrypt
                    SUBCOMMAND=lvm
          - multijob:
             name: 'testing ceph-volume simple'
             condition: SUCCESSFUL
             projects:
               - name: ceph-volume-scenario
                 current-parameters: true
                 predefined-parameters: |
                   SCENARIO=centos7-bluestore-activate
                   SUBCOMMAND=simple
               - name: ceph-volume-scenario
                 current-parameters: true
                 predefined-parameters: |
                   SCENARIO=centos7-filestore-activate
                   SUBCOMMAND=simple
               - name: ceph-volume-scenario
                 current-parameters: true
                 predefined-parameters: |
                   SCENARIO=centos7-bluestore-dmcrypt_luks
                   SUBCOMMAND=simple
               - name: ceph-volume-scenario
                 current-parameters: true
                 predefined-parameters: |
                   SCENARIO=centos7-filestore-dmcrypt_luks
                   SUBCOMMAND=simple
               - name: ceph-volume-scenario
                 current-parameters: true
                 predefined-parameters: |
                   SCENARIO=centos7-bluestore-dmcrypt_plain
                   SUBCOMMAND=simple
               - name: ceph-volume-scenario
                 current-parameters: true
                 predefined-parameters: |
                   SCENARIO=centos7-filestore-dmcrypt_plain
                   SUBCOMMAND=simple
               - name: ceph-volume-scenario
                 current-parameters: true
                 predefined-parameters: |
                   SCENARIO=xenial-bluestore-activate
                   SUBCOMMAND=simple
               - name: ceph-volume-scenario
                 current-parameters: true
                 predefined-parameters: |
                   SCENARIO=xenial-filestore-activate
                   SUBCOMMAND=simple
               - name: ceph-volume-scenario
                 current-parameters: true
                 predefined-parameters: |
                   SCENARIO=xenial-bluestore-dmcrypt_luks
                   SUBCOMMAND=simple
               - name: ceph-volume-scenario
                 current-parameters: true
                 predefined-parameters: |
                   SCENARIO=xenial-filestore-dmcrypt_luks
                   SUBCOMMAND=simple
               - name: ceph-volume-scenario
                 current-parameters: true
                 predefined-parameters: |
                   SCENARIO=xenial-bluestore-dmcrypt_plain
                   SUBCOMMAND=simple
               - name: ceph-volume-scenario
                 current-parameters: true
                 predefined-parameters: |
                   SCENARIO=xenial-filestore-dmcrypt_plain
                   SUBCOMMAND=simple
          - multijob:
              name: 'testing ceph-volume batch'
              condition: SUCCESSFUL
              projects:
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-bluestore-single_type
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-bluestore-single_type_dmcrypt
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-filestore-single_type
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-filestore-single_type_dmcrypt
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-bluestore-mixed_type
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-filestore-mixed_type
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-bluestore-mixed_type_dmcrypt
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-filestore-mixed_type_dmcrypt
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-bluestore-mixed_type_explicit
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-filestore-mixed_type_explicit
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-bluestore-mixed_type_dmcrypt_explicit
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=centos7-filestore-mixed_type_dmcrypt_explicit
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=xenial-bluestore-single_type
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=xenial-bluestore-single_type_dmcrypt
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=xenial-filestore-single_type
                    SUBCOMMAND=batch
                - name: ceph-volume-scenario
                  current-parameters: true
                  predefined-parameters: |
                    SCENARIO=xenial-filestore-single_type_dmcrypt
                    SUBCOMMAND=batch
